// flow-typed signature: 3de13d71b397e270f5b1f1af02f8bbe2
// flow-typed version: <<STUB>>/electron-is-dev_v^1.1.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-is-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// So very hilarious & simple:
declare module 'electron-is-dev' {
  declare module.exports: boolean;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-is-dev/index' {
  declare module.exports: $Exports<'electron-is-dev'>;
}
declare module 'electron-is-dev/index.js' {
  declare module.exports: $Exports<'electron-is-dev'>;
}
