// flow-typed signature: 820fb9d603e74c8d52311c905b5d8ae9
// flow-typed version: <<STUB>>/music-metadata_v^5.2.0/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'music-metadata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'music-metadata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'music-metadata/lib/aiff/AiffParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/aiff/AiffToken' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/aiff' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/apev2/APEv2Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/apev2/APEv2TagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/apev2/APEv2Token' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/apev2' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf/AsfObject' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf/AsfParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf/AsfTagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf/AsfUtil' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf/GUID' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/asf' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/BasicParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/CaseInsensitiveTagMap' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/CombinedTagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/FourCC' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/GenericTagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/GenericTagTypes' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/MetadataCollector' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/RandomBufferReader' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/RandomFileReader' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/Util' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/common/Windows1292Decoder' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/core' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/dsdiff/DsdiffParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/dsdiff/DsdiffToken' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/dsf/DsfChunk' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/dsf/DsfParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ebml/EbmlParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ebml/EbmlTagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ebml/types' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/flac/FlacParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/flac' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v1/ID3v1Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v1/ID3v1TagMap' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/AbstractID3Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/FrameParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/ID3Stream' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/ID3v22TagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/ID3v24TagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/ID3v2Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/id3v2/ID3v2Token' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/iff' {
  declare module.exports: any;
}

declare module 'music-metadata/lib' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/lyrics3/Lyrics3' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mp4/Atom' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mp4/AtomToken' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mp4' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mp4/MP4Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mp4/MP4TagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mpeg' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mpeg/MpegParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/mpeg/XingTag' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack/sv7/BitReader' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack/sv7/MpcSv7Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack/sv7/StreamVersion7' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack/sv8/MpcSv8Parser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/musepack/sv8/StreamVersion8' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/Ogg' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/OggParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/opus/Opus' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/opus/OpusParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/speex/Speex' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/speex/SpeexParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/theora/Theora' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/theora/TheoraParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/vorbis/Vorbis' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/vorbis/VorbisDecoder' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/vorbis/VorbisParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ogg/vorbis/VorbisTagMapper' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/ParserFactory' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/riff' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/riff/RiffChunk' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/riff/RiffInfoTagMap' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/riff/WaveParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/type' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/wav/WaveChunk' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/wavpack' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/wavpack/WavPackParser' {
  declare module.exports: any;
}

declare module 'music-metadata/lib/wavpack/WavPackToken' {
  declare module.exports: any;
}

// Filename aliases
declare module 'music-metadata/lib/aiff/AiffParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/aiff/AiffParser'>;
}
declare module 'music-metadata/lib/aiff/AiffToken.js' {
  declare module.exports: $Exports<'music-metadata/lib/aiff/AiffToken'>;
}
declare module 'music-metadata/lib/aiff/index' {
  declare module.exports: $Exports<'music-metadata/lib/aiff'>;
}
declare module 'music-metadata/lib/aiff/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/aiff'>;
}
declare module 'music-metadata/lib/apev2/APEv2Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/apev2/APEv2Parser'>;
}
declare module 'music-metadata/lib/apev2/APEv2TagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/apev2/APEv2TagMapper'>;
}
declare module 'music-metadata/lib/apev2/APEv2Token.js' {
  declare module.exports: $Exports<'music-metadata/lib/apev2/APEv2Token'>;
}
declare module 'music-metadata/lib/apev2/index' {
  declare module.exports: $Exports<'music-metadata/lib/apev2'>;
}
declare module 'music-metadata/lib/apev2/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/apev2'>;
}
declare module 'music-metadata/lib/asf/AsfObject.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf/AsfObject'>;
}
declare module 'music-metadata/lib/asf/AsfParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf/AsfParser'>;
}
declare module 'music-metadata/lib/asf/AsfTagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf/AsfTagMapper'>;
}
declare module 'music-metadata/lib/asf/AsfUtil.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf/AsfUtil'>;
}
declare module 'music-metadata/lib/asf/GUID.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf/GUID'>;
}
declare module 'music-metadata/lib/asf/index' {
  declare module.exports: $Exports<'music-metadata/lib/asf'>;
}
declare module 'music-metadata/lib/asf/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/asf'>;
}
declare module 'music-metadata/lib/common/BasicParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/BasicParser'>;
}
declare module 'music-metadata/lib/common/CaseInsensitiveTagMap.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/CaseInsensitiveTagMap'>;
}
declare module 'music-metadata/lib/common/CombinedTagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/CombinedTagMapper'>;
}
declare module 'music-metadata/lib/common/FourCC.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/FourCC'>;
}
declare module 'music-metadata/lib/common/GenericTagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/GenericTagMapper'>;
}
declare module 'music-metadata/lib/common/GenericTagTypes.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/GenericTagTypes'>;
}
declare module 'music-metadata/lib/common/MetadataCollector.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/MetadataCollector'>;
}
declare module 'music-metadata/lib/common/RandomBufferReader.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/RandomBufferReader'>;
}
declare module 'music-metadata/lib/common/RandomFileReader.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/RandomFileReader'>;
}
declare module 'music-metadata/lib/common/Util.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/Util'>;
}
declare module 'music-metadata/lib/common/Windows1292Decoder.js' {
  declare module.exports: $Exports<'music-metadata/lib/common/Windows1292Decoder'>;
}
declare module 'music-metadata/lib/core.js' {
  declare module.exports: $Exports<'music-metadata/lib/core'>;
}
declare module 'music-metadata/lib/dsdiff/DsdiffParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/dsdiff/DsdiffParser'>;
}
declare module 'music-metadata/lib/dsdiff/DsdiffToken.js' {
  declare module.exports: $Exports<'music-metadata/lib/dsdiff/DsdiffToken'>;
}
declare module 'music-metadata/lib/dsf/DsfChunk.js' {
  declare module.exports: $Exports<'music-metadata/lib/dsf/DsfChunk'>;
}
declare module 'music-metadata/lib/dsf/DsfParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/dsf/DsfParser'>;
}
declare module 'music-metadata/lib/ebml/EbmlParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ebml/EbmlParser'>;
}
declare module 'music-metadata/lib/ebml/EbmlTagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/ebml/EbmlTagMapper'>;
}
declare module 'music-metadata/lib/ebml/types.js' {
  declare module.exports: $Exports<'music-metadata/lib/ebml/types'>;
}
declare module 'music-metadata/lib/flac/FlacParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/flac/FlacParser'>;
}
declare module 'music-metadata/lib/flac/index' {
  declare module.exports: $Exports<'music-metadata/lib/flac'>;
}
declare module 'music-metadata/lib/flac/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/flac'>;
}
declare module 'music-metadata/lib/id3v1/ID3v1Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v1/ID3v1Parser'>;
}
declare module 'music-metadata/lib/id3v1/ID3v1TagMap.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v1/ID3v1TagMap'>;
}
declare module 'music-metadata/lib/id3v2/AbstractID3Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/AbstractID3Parser'>;
}
declare module 'music-metadata/lib/id3v2/FrameParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/FrameParser'>;
}
declare module 'music-metadata/lib/id3v2/ID3Stream.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/ID3Stream'>;
}
declare module 'music-metadata/lib/id3v2/ID3v22TagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/ID3v22TagMapper'>;
}
declare module 'music-metadata/lib/id3v2/ID3v24TagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/ID3v24TagMapper'>;
}
declare module 'music-metadata/lib/id3v2/ID3v2Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/ID3v2Parser'>;
}
declare module 'music-metadata/lib/id3v2/ID3v2Token.js' {
  declare module.exports: $Exports<'music-metadata/lib/id3v2/ID3v2Token'>;
}
declare module 'music-metadata/lib/iff/index' {
  declare module.exports: $Exports<'music-metadata/lib/iff'>;
}
declare module 'music-metadata/lib/iff/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/iff'>;
}
declare module 'music-metadata/lib/index' {
  declare module.exports: $Exports<'music-metadata/lib'>;
}
declare module 'music-metadata/lib/index.js' {
  declare module.exports: $Exports<'music-metadata/lib'>;
}
declare module 'music-metadata/lib/lyrics3/Lyrics3.js' {
  declare module.exports: $Exports<'music-metadata/lib/lyrics3/Lyrics3'>;
}
declare module 'music-metadata/lib/mp4/Atom.js' {
  declare module.exports: $Exports<'music-metadata/lib/mp4/Atom'>;
}
declare module 'music-metadata/lib/mp4/AtomToken.js' {
  declare module.exports: $Exports<'music-metadata/lib/mp4/AtomToken'>;
}
declare module 'music-metadata/lib/mp4/index' {
  declare module.exports: $Exports<'music-metadata/lib/mp4'>;
}
declare module 'music-metadata/lib/mp4/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/mp4'>;
}
declare module 'music-metadata/lib/mp4/MP4Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/mp4/MP4Parser'>;
}
declare module 'music-metadata/lib/mp4/MP4TagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/mp4/MP4TagMapper'>;
}
declare module 'music-metadata/lib/mpeg/index' {
  declare module.exports: $Exports<'music-metadata/lib/mpeg'>;
}
declare module 'music-metadata/lib/mpeg/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/mpeg'>;
}
declare module 'music-metadata/lib/mpeg/MpegParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/mpeg/MpegParser'>;
}
declare module 'music-metadata/lib/mpeg/XingTag.js' {
  declare module.exports: $Exports<'music-metadata/lib/mpeg/XingTag'>;
}
declare module 'music-metadata/lib/musepack/index' {
  declare module.exports: $Exports<'music-metadata/lib/musepack'>;
}
declare module 'music-metadata/lib/musepack/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack'>;
}
declare module 'music-metadata/lib/musepack/sv7/BitReader.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack/sv7/BitReader'>;
}
declare module 'music-metadata/lib/musepack/sv7/MpcSv7Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack/sv7/MpcSv7Parser'>;
}
declare module 'music-metadata/lib/musepack/sv7/StreamVersion7.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack/sv7/StreamVersion7'>;
}
declare module 'music-metadata/lib/musepack/sv8/MpcSv8Parser.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack/sv8/MpcSv8Parser'>;
}
declare module 'music-metadata/lib/musepack/sv8/StreamVersion8.js' {
  declare module.exports: $Exports<'music-metadata/lib/musepack/sv8/StreamVersion8'>;
}
declare module 'music-metadata/lib/ogg/index' {
  declare module.exports: $Exports<'music-metadata/lib/ogg'>;
}
declare module 'music-metadata/lib/ogg/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg'>;
}
declare module 'music-metadata/lib/ogg/Ogg.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/Ogg'>;
}
declare module 'music-metadata/lib/ogg/OggParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/OggParser'>;
}
declare module 'music-metadata/lib/ogg/opus/Opus.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/opus/Opus'>;
}
declare module 'music-metadata/lib/ogg/opus/OpusParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/opus/OpusParser'>;
}
declare module 'music-metadata/lib/ogg/speex/Speex.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/speex/Speex'>;
}
declare module 'music-metadata/lib/ogg/speex/SpeexParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/speex/SpeexParser'>;
}
declare module 'music-metadata/lib/ogg/theora/Theora.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/theora/Theora'>;
}
declare module 'music-metadata/lib/ogg/theora/TheoraParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/theora/TheoraParser'>;
}
declare module 'music-metadata/lib/ogg/vorbis/Vorbis.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/vorbis/Vorbis'>;
}
declare module 'music-metadata/lib/ogg/vorbis/VorbisDecoder.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/vorbis/VorbisDecoder'>;
}
declare module 'music-metadata/lib/ogg/vorbis/VorbisParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/vorbis/VorbisParser'>;
}
declare module 'music-metadata/lib/ogg/vorbis/VorbisTagMapper.js' {
  declare module.exports: $Exports<'music-metadata/lib/ogg/vorbis/VorbisTagMapper'>;
}
declare module 'music-metadata/lib/ParserFactory.js' {
  declare module.exports: $Exports<'music-metadata/lib/ParserFactory'>;
}
declare module 'music-metadata/lib/riff/index' {
  declare module.exports: $Exports<'music-metadata/lib/riff'>;
}
declare module 'music-metadata/lib/riff/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/riff'>;
}
declare module 'music-metadata/lib/riff/RiffChunk.js' {
  declare module.exports: $Exports<'music-metadata/lib/riff/RiffChunk'>;
}
declare module 'music-metadata/lib/riff/RiffInfoTagMap.js' {
  declare module.exports: $Exports<'music-metadata/lib/riff/RiffInfoTagMap'>;
}
declare module 'music-metadata/lib/riff/WaveParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/riff/WaveParser'>;
}
declare module 'music-metadata/lib/type.js' {
  declare module.exports: $Exports<'music-metadata/lib/type'>;
}
declare module 'music-metadata/lib/wav/WaveChunk.js' {
  declare module.exports: $Exports<'music-metadata/lib/wav/WaveChunk'>;
}
declare module 'music-metadata/lib/wavpack/index' {
  declare module.exports: $Exports<'music-metadata/lib/wavpack'>;
}
declare module 'music-metadata/lib/wavpack/index.js' {
  declare module.exports: $Exports<'music-metadata/lib/wavpack'>;
}
declare module 'music-metadata/lib/wavpack/WavPackParser.js' {
  declare module.exports: $Exports<'music-metadata/lib/wavpack/WavPackParser'>;
}
declare module 'music-metadata/lib/wavpack/WavPackToken.js' {
  declare module.exports: $Exports<'music-metadata/lib/wavpack/WavPackToken'>;
}
