export enum Keys {
  AddFileLocation = 'O',
  SavePlaylist = 'S',
  Find = 'F',
  NowPlaying = '1',
  Albums = '2',
  Artists = '3',
  Songs = '4',
  Playlists = '5',
  ToggleMiniPlayer = '9',
  Settings = ',',
  Play = 'P',
  PreviousTrack = 'Left',
  NextTrack = 'Right',
  Shuffle = 'R',
  Repeat = 'T',
  Forward10s = ']',
  Backward10s = '[',
}
