export enum IpcId {
  ClearHates = 'clear-hates',
  ClearLikes = 'clear-likes',
  DeletePlaylist = 'delete-playlist',
  FlushImageCache = 'flush-image-cache',
  GetHates = 'get-hates',
  GetLikes = 'get-likes',
  GetMediaInfo = 'media-info',
  GetMusicDatabase = 'get-music-database',
  GetPlaylists = 'get-playlists',
  LoadPlaylists = 'load-playlists',
  ManualRescan = 'manual-rescan',
  MusicDBUpdate = 'music-database-update',
  RenamePlaylist = 'rename-playlist',
  SavePlaylist = 'save-playlist',
  Search = 'search',
  SetHates = 'set-hates',
  SetLikes = 'set-likes',
  SetMediaInfo = 'set-media-info',
  SetPlaylists = 'set-playlists',
  SetSaveMenu = 'set-save-menu',
  ShowFile = 'show-file',
  ShowLocFromKey = 'show-location-from-key',
  SubstrSearch = 'subsearch',
  UploadImage = 'upload-image',
}

export enum Keys {
  AddFileLocation = 'O',
  Albums = '2',
  Artists = '3',
  Backward10s = '[',
  Find = 'F',
  Forward10s = ']',
  NextTrack = 'Right',
  NowPlaying = '1',
  Play = 'P',
  Playlists = '5',
  PreviousTrack = 'Left',
  Repeat = 'T',
  SavePlaylist = 'S',
  Settings = ',',
  Shuffle = 'R',
  Songs = '4',
  ToggleMiniPlayer = '9',
}
